FROM node:16.17-alpine

WORKDIR /code

RUN corepack enable

RUN corepack prepare pnpm@latest --activate

COPY .npmrc /code/.npmrc

COPY turbo.json /code/turbo.json

COPY tsconfig.json /code/tsconfig.json

COPY package.json /code/package.json

COPY pnpm-lock.yaml /code/pnpm-lock.yaml

COPY pnpm-workspace.yaml /code/pnpm-workspace.yaml

COPY apps/web/package.json /code/apps/web/package.json

COPY apps/web/src /code/apps/web/src

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
      pnpm fetch

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
     pnpm install -r --offline

CMD pnpm dev:web