name: 'Push to the Docker registry'
description: 'Push to the Docker registry'
inputs:
  app-name:
    description: 'The name of the app to push, should match the folder name in apps/'
    required: true
  digitalocean-access-token:
    description: 'The DigitalOcean access token'
    required: true
  build-args:
    description: 'The build args to pass to the Docker build'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.digitalocean-access-token }}
    - name: Login to Registry
      shell: sh
      run: doctl registry login
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        target: prod
        file: apps/${{ inputs.app-name }}/Dockerfile
        push: true
        tags: registry.digitalocean.com/regels-overheid-nl/${{ inputs.app-name }}:${{ github.sha }},registry.digitalocean.com/regels-overheid-nl/${{ inputs.app-name }}:latest
        build-args: ${{ inputs.build-args }}
  