services:
  cms:
    restart: always
    build:
      context: .
      dockerfile: apps/cms/dockerfile.prod
    ports:
      - 9001:9001
    env_file:
      - .env
  web:
    restart: always
    environment:
      - CMS_API=http://host.docker.internal:9001/api
    build:
      context: .
      dockerfile: apps/web/dockerfile.prod
    ports:
      - 9000:9000
  nginx:
    depends_on:
      - cms
    restart: always
    ports:
      - 80:80
    build:
      context: ./apps/nginx
      dockerfile: dockerfile.prod
