site_name: Open Regels
site_url: https://open-regels.nl/

# Repository
repo_name: regels.overheid.nl
repo_url: https://gitlab.com/discipl/RON/regels.overheid.nl

# Hide the edit button
edit_uri: edit/edited_via_edit_button/docs/

nav:
    - Home: index.md
    - Content: contentkalender.md
    - Methoden:
        - Wetsanalyse: methoden/wetsanalyse.md
        - ALEF: methoden/ALEF.md
        - RegelSpraak: methoden/RegelSpraak.md
        - GPF: methoden/GPF.md
        - DMN: methoden/DMN.md
        - FLINT: methoden/FLINT.md
    - NLX:
        - Introductie: nlx/nlx-intro.md
        - Demo Setup: nlx/nlx-setup.md
    - Over:
        - Introductie: intro.md
        - Open Innovatie: open-innovatie.md
        - Manifest: manifest.md
        - Partners:
          - Financieel Paspoort: partners/FP.md

theme: 
  name: material
  language: nl
  palette:
    primary: indigo
  features:
    - navigation.tracking
    - navigation.tabs
  icon:
    repo: fontawesome/brands/gitlab

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Nederlands
      link: /nl/
      lang: nl

  analytics:
    provider: google
    property: G-Q0N2DM4ZBX

plugins:
  - tags
  - search:
      lang: 
        - nl
        - en
  - i18n:
      default_language: nl
      languages:
        default:
          name: Default (nl)
          build: true
        nl:
          name: Nederlands
          build: true
          site_name: "Open Regels"
        en:
          name: English
          build: true
          site_name: "Open Rules"
      nav_translations:
        en:
          Methoden: Methods
          Wetsanalyse: Law analysis
          Over: About
          Introductie: Introduction
          
