packages:
  - apps/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@strapi/strapi'
  - core-js
  - core-js-pure
  - es5-ext
  - puppeteer
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
