packages:
  - 'apps/*'
overrides:
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
