FROM node:16.17-alpine

WORKDIR /code

RUN corepack enable

RUN corepack prepare pnpm@latest --activate

COPY .npmrc /code/.npmrc

COPY turbo.json /code/turbo.json

COPY tsconfig.json /code/tsconfig.json

COPY package.json /code/package.json

COPY pnpm-lock.yaml /code/pnpm-lock.yaml

COPY pnpm-workspace.yaml /code/pnpm-workspace.yaml

COPY apps/docs/package.json /code/apps/docs/package.json

COPY apps/docs/docusaurus.config.js /code/apps/docs/docusaurus.config.js

COPY apps/docs/sidebars.js /code/apps/docs/sidebars.js

COPY apps/docs/docs /code/apps/docs/docs

COPY apps/docs/src /code/apps/docs/src

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
      pnpm fetch

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
     pnpm install -r

CMD pnpm dev:docs