# ==== Builder ====
FROM node:18-alpine as builder

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

RUN yarn global add turbo

COPY . .

RUN turbo prune --scope=@regels-overheid/docs --docker

# ==== Installer ====
FROM node:18-alpine AS installer

RUN apk add --no-cache libc6-compat
RUN apk update

WORKDIR /app

COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/yarn.lock ./yarn.lock

RUN yarn install


# ==== Runner ====
FROM node:18-alpine AS runner

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 app

USER app

COPY --from=builder --chown=app:nodejs /app/out/full/apps/docs .
COPY --from=installer --chown=app:nodejs /app/node_modules ./node_modules

CMD yarn dev