name: 'Upgrade Helm release'
description: 'Upgrade Helm release'
inputs:
  app-name:
    description: 'The name of the app to push, should match the folder name in apps/'
    required: true
  release-name:
    description: 'The name of the Helm release to upgrade'
    required: true
  digitalocean-access-token:
    description: 'The DigitalOcean access token'
    required: true
  cluster-id:
    description: 'The ID of the Digital Ocean cluster to deploy to'
    required: true
  namespace:
    description: 'The namespace to deploy to'
    required: true
    default: 'app'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.digitalocean-access-token }}
    - name: Retrieve Kubeconfig
      shell: sh
      run: doctl kubernetes cluster kubeconfig save ${{ inputs.cluster-id }}
    - name: Install Helm
      shell: sh
      run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Add Helm repo
      shell: sh
      run: helm repo add regels-overheid-nl https://minbzk.github.io/helm.regels.overheid.nl/
    - name: Upgrade Helm release
      shell: sh
      run: |
        helm upgrade --install --atomic --wait ${{ inputs.release-name }} regels-overheid-nl/${{ inputs.app-name }} --namespace ${{ inputs.namespace }} --set image.tag=${{ github.sha }} -f ./.github/configs/production/${{ inputs.app-name}}/values.yml