name: 'Run workspace script'
inputs:
  workspace:
    required: true
  script:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.9.0
        run_install: false
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: 20.11
    - run: pnpm install
      shell: bash
    - run: pnpm --filter=${{ inputs.workspace }} ${{ inputs.script }}
      shell: bash
