FROM node:16.17.0

WORKDIR /code

RUN corepack enable

RUN corepack prepare pnpm@latest --activate

COPY .npmrc pnpm-lock.yaml package.json pnpm-workspace.yaml ./

COPY apps/cms/package.json /code/apps/cms/package.json

COPY apps/web/package.json /code/apps/web/package.json

COPY apps/docs/package.json /code/apps/docs/package.json

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store\
     pnpm install --shamefully-hoist --config.auto-install-peers=true

ADD . .

RUN PUBLIC_URL="http://cms.localhost" pnpm build:cms

CMD pnpm dev:cms
