# ==== Base ====
FROM node:18-alpine as base

RUN apk add --no-cache libc6-compat
RUN apk update
RUN yarn global add turbo
# ==== Builder ====
FROM base as builder

WORKDIR /code

COPY . .

RUN turbo prune --scope=@regels-overheid/cms --docker
# ==== Installer ====
FROM base AS installer

WORKDIR /code

COPY .gitignore .gitignore
COPY --from=builder /code/out/json/ .
COPY --from=builder /code/out/yarn.lock ./yarn.lock

RUN yarn install
# ==== Runner ====
FROM base AS runner

WORKDIR /code

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 app

USER app

COPY --from=builder --chown=app:nodejs /code/out/yarn.lock ./yarn.lock
COPY --from=builder --chown=app:nodejs /code/out/full .
COPY --from=installer --chown=app:nodejs /code/node_modules ./node_modules

ENV PUBLIC_URL http://cms.localhost

RUN yarn build

CMD yarn dev