name: Publish Respec document to regels.overheid.nl
inputs:
  token:
    description: "The secret publication token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract repository name and send notify request
      id: request
      shell: bash
      run: |
        REPO_NAME="${GITHUB_REPOSITORY##*/}"
        echo "Extracted Repository Name: $REPO_NAME"
        RESPONSE=$(curl -s -X POST -H "Content-Type: application/json" -d '{"owner":"${{ github.repository_owner }}","repo":"'$REPO_NAME'","secret":"${{ inputs.token }}"}' "https://regels.overheid.nl/api/publications")
        echo "::set-output name=response::$RESPONSE"
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.token }}
    - name: Validate notify response
      if: fromJSON(steps.request.outputs.response).ok != true
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Request failed with response: ${{ steps.request.outputs.response }}')
