name: Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - 'apps/docs/CHANGELOG.md'
      - '.github/workflows/deploy-docs.yml'
jobs:
  build-docs-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-docker
        with:
          app-name: docs
          digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  deploy-docs-image:
    runs-on: ubuntu-latest
    needs: build-docs-image
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/upgrade-helm
        with:
          app-name: docs
          release-name: docs
          digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          cluster-id: ${{ secrets.DIGITALOCEAN_PRODUCTION_CLUSTER_ID }}
          secrets: '${{ toJson(secrets) }}'
