name: PR checks for apps/web
on:
  pull_request:
    paths:
      - 'apps/web/**'
jobs:
  common-web-jobs:
    uses: MinBZK/regels.overheid.nl/.github/workflows/common-web-jobs.yml@main
    with:
      working-directory: apps/web
