name: PR checks for apps/cms
on:
  pull_request:
    paths:
      - 'apps/cms/**'
jobs:
  common-web-jobs:
    uses: MinBZK/regels.overheid.nl/.github/workflows/common-web-jobs.yml@main
    with:
      working-directory: apps/cms
