name: Validate pull request (web)

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: onursagir/regels.overheid.nl/run-workspace-script
  typecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: onursagir/regels.overheid.nl/run-workspace-script
  stylecheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: onursagir/regels.overheid.nl/run-workspace-script
  build:
    needs: [lint, typecheck, stylecheck]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build (Docker)
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          file: ./apps/web/Dockerfile
          push: false
